feat: add gogoanime, colored output

diff --git a/extractors/doodstream b/extractors/doodstream
--- a/extractors/doodstream
+++ b/extractors/doodstream
@@ -10,9 +10,9 @@ dood_id=$(printf "$*" | sed -nE "s_.*dood.*/[e|d]/([^?]*).*_\1_p")
 dood_link="https://dood.ws"
 
 
-[ -z "$dood_id" ] && printf "[ doodstream ] Invalid link\n" && exit 1
+[ -z "$dood_id" ] && printf "\033[1;31m[ doodstream ] Invalid link\n" && exit 1
 
-printf "[ doodstream ] [ $dood_id ] Downloading webpage\n"
+printf "\033[1;36m[ doodstream ] [ $dood_id ] Downloading webpage\n"
 #fetching first link and title
 data=$(curl --cipher AES256-SHA256 --tls-max 1.2 -s -A "$agent" "$dood_link/e/$dood_id" | sed -nE "s|.*>([^<]*)</title.*(/pass_md5[^']*)',.*|\1\n\2|p")
 
@@ -21,16 +21,16 @@ title=$(printf "%s" "$data" | head -1)
 hash_part=$(printf "%s" "$data" | tail -1)
 token=$(echo $hash_part | cut -d "/" -f4)
 
-printf "[ doodstream ] [ $dood_id ] Fetching Video url\n"
+printf "\033[1;36m[ doodstream ] [ $dood_id ] Fetching Video url\n"
 #final url prefix part
 video_url=$(curl --cipher AES256-SHA256 --tls-max 1.2 -s -A "$agent" "${dood_link}${hash_part}" -e "$dood_link")
 
 #final url
 if [ -n "$video_url" ];then
-    printf "Name >> %s\n" "$title"
-    printf "referer >> %s\n" "$dood_link"
-    printf "URL >> %sdoodstream?token=%s&expiry=%s\n" "$video_url" "$token" "$(date +'%s%3N')"
-    printf "\n"
+    printf "\033[1;32m Name >>\033[0m %s\n" "$title"
+    printf "\033[1;32m referer >>\033[0m %s\n" "$dood_link"
+    printf "\033[1;32m URL >>\033[0m %sdoodstream?token=%s&expiry=%s\n" "$video_url" "$token" "$(date +'%s%3N')"
+    printf "\033[0m\n"
 else
-    printf "[ doodstream ] [ $dood_id ] Cannot fetch final url\n\n"
+    printf "\033[1;31m[ doodstream ] [ $dood_id ] Cannot fetch final url\033[0m\n\n"
 fi
diff --git a/extractors/fembed b/extractors/fembed
--- a/extractors/fembed
+++ b/extractors/fembed
@@ -8,21 +8,21 @@ agent="Mozilla/5.0 (Linux; Android 11; moto g(9) power) AppleWebKit/537.36 (KHTM
 #extracting fembed id from arguments
 fb_id=$(printf "$*" | sed -nE "s_.*[fembed|embedsito].*/[v|f]/([^#]*).*_\1_p")
 
-[ -z "$fb_id" ] && printf "[ fembed ] Invalid link\n" && exit 1
+[ -z "$fb_id" ] && printf "\033[1;31m[ fembed ] Invalid link\n" && exit 1
 
-printf "[ fembed ] [ $fb_id ] Downloading webpage\n"
+printf "\033[1;36m[ fembed ] [ $fb_id ] Downloading webpage\n"
 #fetching title
 title=$(curl -s "$*" -A "$agent" | sed -nE "s|.*>(Video )?([^<]*)</title.*|\2|p")
 
-printf "[ fembed ] [ $fb_id ] Fetching video url\n"
+printf "\033[1;36m[ fembed ] [ $fb_id ] Fetching video url\n"
 #main logic
 video_url=$(curl -A "$agent" -s -X POST "https://fembed-hd.com/api/source/$fb_id" -H "x-requested-with:XMLHttpRequest" | tr '{|}' '\n' | sed -nE 's/.*file":"([^"]*)","label":"([^"]*)".*/\2 > \1/p' | tr -d '\\')
 
 if [ -n "$video_url" ];then
-    printf "Name >> %s\n" "$title"
-    printf "referer >> %s\n" "$*"
-    printf "URL >>\n%s\n" "$video_url"
+    printf "\033[1;32m Name >>\033[0m %s\n" "$title"
+    printf "\033[1;32m referer >>\033[0m %s\n" "$*"
+    printf "\033[1;32m URL >>\033[0m\n%s\n" "$video_url"
     printf "\n"
 else
-    printf "[ fembed ] [ $fb_id ] Cannot fetch final url\n\n"
+    printf "\033[1;32m[ fembed ] [ $fb_id ] Cannot fetch final url\033[0m\n\n"
 fi
diff --git a/extractors/membed b/extractors/membed
--- a/extractors/membed
+++ b/extractors/membed
@@ -10,9 +10,9 @@ agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ch
 sub_url=$(printf "%s" "$*" | cut -d'/' -f5)
 
 #check if id is empty
-[ -z "$sub_url" ] && printf "[ membed ] Invalid link\n" && exit 1
+[ -z "$sub_url" ] && printf "\033[1;31m[ membed ] Invalid link\n" && exit 1
 
-printf "[ membed ] [ $sub_url ] Downloading webpage\n"
+printf "\033[1;36m[ membed ] [ $sub_url ] Downloading webpage\n"
 refr=$(curl -A "$agent" -s "$base_url/videos/$sub_url" | sed -nE 's/.*iframe src="(.*)" al.*/\1/p')
 
 #extracting subtitle link if it contains subtitles
@@ -28,18 +28,18 @@ secret_key="3235373432353332353932313338343936373434363635383739383833323831"
 #ajax building for fetching video links
 ajax=$(printf "%s" "$refr" | sed -nE 's/.*id=([^&]*)&.*/\1/p' | openssl enc -e -aes256 -K "$secret_key" -iv "$iv" -a)
 
-printf "[ membed ] [ $sub_url ] Fetching video url\n"
+printf "\033[1;36m[ membed ] [ $sub_url ] Fetching video url\n"
 #fetching video links, then decrypting it using openssl
 video_url=$(curl -A "$agent" -s -H "X-Requested-With:XMLHttpRequest" "${base_url}/encrypt-ajax.php?id=${ajax}" | sed -e 's/{"data":"//' -e 's/"}/\n/' -e 's/\\//g' | base64 -d | openssl enc -d -aes256 -K "$secret_key" -iv "$iv" | tr -d '\\' | sed -nE 's_.*file":"([^"]*)".*source.*_\1_p')
 
 if [ -n "$video_url" ];then
-    printf "Name >> %s\n" "$sub_url"
-    printf "referer >> %s\n" "$*"
-    printf "URL >> %s\n" "$video_url"
-    [ -z "$subtitle" ] || printf "Subtitle_url >> %s\n" "https://msubload.com/sub$subtitle"
+    printf "\033[1;32m Name >>\033[0m %s\n" "$sub_url"
+    printf "\033[1;32m referer >>\033[0m %s\n" "$*"
+    printf "\033[1;32m URL >>\033[0m %s\n" "$video_url"
+    [ -z "$subtitle" ] || printf "\033[1;32m Subtitle_url >>\033[0m %s\n" "https://msubload.com/sub$subtitle"
     printf "\n"
 else
-    printf "[ membed ] [ $sub_url ] Cannot fetch final url\n\n"
+    printf "\033[1;31m[ membed ] [ $sub_url ] Cannot fetch final url\033[0m\n\n"
 fi
 
 fb_id=$(printf "%s" "$resp" | sed -n '/fembed/p;/embedsito/p')
diff --git a/extractors/youtube b/extractors/youtube
--- a/extractors/youtube
+++ b/extractors/youtube
@@ -6,7 +6,7 @@
 id=$(printf "$*" | cut -d"=" -f2 | cut -d"/" -f4)
 
 #check if id exists
-[ -z "$id" ] && printf "[ youtube ] Invalid link\n" && exit 1
+[ -z "$id" ] && printf "\033[1;31m[ youtube ] Invalid link\n" && exit 1
 
 #user-agent
 agent="com.google.android.youtube/17.31.35 (Linux; U; Android 11) gzip"
@@ -34,7 +34,7 @@ json="{
   \"racyCheckOk\": true
 }"
 
-printf "[ youtube ] [ $id ] Extracting video url\n"
+printf "\033[1;36m[ youtube ] [ $id ] Extracting video url\n"
 #main logic
 data=$(curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.115 Safari/537.36" -s "https://www.youtube.com/watch?v=$id&bpctr=9999999999&has_verified=1" -o /dev/null -c - | curl -X POST -A "$agent" -s "https://www.youtube.com/youtubei/v1/player?key=AIzaSyA8eiZmM1FaDVjRy-df2KTyQ_vz_yYM39w&prettyPrint=false" -H "content-type:application/json" -H "x-youtube-client-name:3" -H "x-youtube-client-version:17.31.35" -d "$json" -b -)
 
@@ -43,11 +43,11 @@ separate_video_audio_url=$(printf "%s" "$data" | jq '.streamingData.adaptiveForm
 title=$(printf "%s" "$data" | jq '.videoDetails.title' -r)
 
 if [ -n "$combined_video_audio_url" ] || [ -n "$seperate_video_audio_url" ];then
-    printf "Name >> %s\n" "$title"
-    printf "referer >> %s\n" "$*"
-    printf "URL >>\nVideo Quality\t| Audio Bitrate\t|\t\t\tmimetype\t\t\t|\tvideo_url\n"
+    printf "\033[1;32m Name >>\033[0m %s\n" "$title"
+    printf "\033[1;32m referer >>\033[0m %s\n" "$*"
+    printf "\033[1;32m URL >>\nQuality\t| Audio Bitrate\t|\t\t\tmimetype\t\t\t|\tvideo_url\033[0m\n"
     printf "%s\n%s" "$combined_video_audio_url" "$separate_video_audio_url"
     printf "\n"
 else
-    printf "[ youtube ] [ $id ] Cannot fetch final urls\n\n"
+    printf "\033[1;31m[ youtube ] [ $id ] Cannot fetch final urls\n\n"
 fi
