feat:minor changes, added membed script

diff --git a/extractors/doodstream b/extractors/doodstream
--- a/extractors/doodstream
+++ b/extractors/doodstream
@@ -6,9 +6,13 @@
 agent="Mozilla/5.0 (Linux; Android 11; moto g(9) power) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/101.0.4951.41 Mobile Safari/537.36"
 
 ##id extraction from arguments
-dood_id=$(printf "$*" | sed -n "s_.*dood.*/e/__p")
+dood_id=$(printf "$*" | sed -nE "s_.*dood.*/[e|d]/([^?]*).*_\1_p")
 dood_link="https://dood.ws"
 
+
+[ -z "$dood_id" ] && printf "[ doodstream ] Invalid link\n" && exit 1
+
+printf "[ doodstream ] [ $dood_id ] Downloading webpage\n"
 #fetching first link and title
 data=$(curl --cipher AES256-SHA256 --tls-max 1.2 -s -A "$agent" "$dood_link/e/$dood_id" | sed -nE "s|.*>([^<]*)</title.*(/pass_md5[^']*)',.*|\1\n\2|p")
 
@@ -17,14 +21,16 @@ title=$(printf "%s" "$data" | head -1)
 hash_part=$(printf "%s" "$data" | tail -1)
 token=$(echo $hash_part | cut -d "/" -f4)
 
+printf "[ doodstream ] [ $dood_id ] Fetching Video url\n"
 #final url prefix part
-url=$(curl --cipher AES256-SHA256 --tls-max 1.2 -s -A "$agent" "${dood_link}${hash_part}" -e "$dood_link")
+video_url=$(curl --cipher AES256-SHA256 --tls-max 1.2 -s -A "$agent" "${dood_link}${hash_part}" -e "$dood_link")
 
 #final url
-if [ -n "$url" ];then
+if [ -n "$video_url" ];then
     printf "Name >> %s\n" "$title"
     printf "referer >> %s\n" "$dood_link"
-    printf "URL >>\n %sdoodstream?token=%s&expiry=%s\n" "$url" "$token" "$(date +'%s%3N')"
+    printf "URL >> %sdoodstream?token=%s&expiry=%s\n" "$video_url" "$token" "$(date +'%s%3N')"
+    printf "\n"
 else
-    printf "Cannot fetch final url"
+    printf "[ doodstream ] [ $dood_id ] Cannot fetch final url\n\n"
 fi
diff --git a/extractors/instagram b/extractors/instagram
--- a/extractors/instagram
+++ b/extractors/instagram
@@ -2,14 +2,17 @@
 
 #shell script for extracting public videos URL from instagram
 
+res=0 #setting result value to zero
+id="$(printf "$*" | sed -nE 's_.*instagram.*/p/([^/]*)/_\1_p')" #ID taken from arguments
+
+#check if id exists
+[ -z "$id" ] && printf "[ instagram ] Invalid link\n" && exit 1
+
 #encoding characters
 enc_char="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_"
 
 #creating table
 table=$(printf "$enc_char" | sed 's/\(.\)/\1\n/g' | nl -v0 | tr '\t' ':' | tr -d ' ')
-
-res=0 #setting result value to zero
-id="$(printf "$*" | sed -nE 's_.*instagram.*/p/([^/]*)/_\1_p')" #ID taken from arguments
 
 #looping at every character
 for key in $(printf "$id" | sed -e 's/\(.\)/\1\n/g');do 
@@ -19,9 +22,16 @@ for key in $(printf "$id" | sed -e 's/\(.\)/\1\n/g');do
     res=$((res*64+value))
 done
 
-printf "$id -> $res\n"
-
 agent="Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"
 
+printf "[ instagram ] [ $id ] Extracting video url\n"
 #main extraction code
-curl -s "https://i.instagram.com/api/v1/web/get_ruling_for_content/?content_type=MEDIA&target_id=$res" -H "x-asbd-id:198387" -H "x-ig-app-id:936619743392459" -H "x-ig-www-claim:0" -A "$agent" -c - -o /dev/null | curl -s "https://www.instagram.com/graphql/query/?query_hash=9f8827793ef34641b2fb195d4d41151c&variables=%7B%22shortcode%22%3A%22$id%22%2C%22include_reel%22%3Afalse%2C%22include_logged_out%22%3Atrue%7D" -H "x-asbd-id:198387" -H "x-ig-app-id:936619743392459" -H "x-ig-www-claim:0" -H "x-requested-with:XMLHttpRequest" -e "https://www.instagram.com/p/$id/" -A "$agent" -b - | tr '{|}' '\n' | sed -nE 's|.*video_url":"([^"]*)".*|\1|p' | sed 's/\u0026/\&/g' | tr -d '\\'
+video_url=$(curl -s "https://i.instagram.com/api/v1/web/get_ruling_for_content/?content_type=MEDIA&target_id=$res" -H "x-asbd-id:198387" -H "x-ig-app-id:936619743392459" -H "x-ig-www-claim:0" -A "$agent" -c - -o /dev/null | curl -s "https://www.instagram.com/graphql/query/?query_hash=9f8827793ef34641b2fb195d4d41151c&variables=%7B%22shortcode%22%3A%22$id%22%2C%22include_reel%22%3Afalse%2C%22include_logged_out%22%3Atrue%7D" -H "x-asbd-id:198387" -H "x-ig-app-id:936619743392459" -H "x-ig-www-claim:0" -H "x-requested-with:XMLHttpRequest" -e "https://www.instagram.com/p/$id/" -A "$agent" -b - | tr '{|}' '\n' | sed -nE 's|.*video_url":"([^"]*)".*|\1|p' | sed 's/\u0026/\&/g' | tr -d '\\')
+
+if [ -n "$video_url" ];then
+    printf "referer >> %s\n" "$*"
+    printf "URL >> %s\n" "$video_url"
+    printf "\n"
+else
+    printf "[ instagram ] [ $id ] Cannot fetch final url\n\n"
+fi
